name: bonnie_invest
description: My graduation project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  banner: ^0.1.3
  banner_view: "^1.1.2"
  fluttertoast: ^3.0.3
  shared_preferences: ^0.4.3
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  flutter_refresh: ^0.0.1
  event_bus: "^1.1.0"
  http: ^0.12.0+2
  groovin_material_icons: ^1.1.6
  sqflite: ^1.1.0
  path_provider: ^0.4.1
  built_value: ^6.4.0
  json_annotation: ^2.0.0
  image_picker: ^0.4.12+1
  permission: ^0.1.1
  simple_permissions: ^0.1.9
  flutter_screenutil: ^0.3.0
  image: ^2.0.7
  date_format: ^1.0.4
  carousel_slider: ^0.0.7
  datetime_picker_formfield: ^0.1.8

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.2.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/story/01/01.jpg
    - images/story/01/02.jpg
    - images/story/01/03.jpg
    - images/story/01/04.jpg
    - images/story/01/05.jpg
    - images/story/01/06.jpg
    - images/story/01/07.jpg
    - images/story/01/08.jpg
    - images/cover/01.jpg
    - images/cover/02.jpg
    - images/cover/03.jpg
    - images/cover/04.jpg
    - images/cover/05.jpg
    - images/cover/06.jpg
    - images/banner1.jpg
    - images/banner2.jpg
    - images/banner3.jpg
    - images/banner4.jpg
    - images/banner5.jpg
    - images/banner6.jpg

    - images/ic_arrow_right.png
    - images/ic_avatar_default.png
    - images/popo1.jpg
    - images/popo2.jpg
    - images/yyyy.jpg
    - images/game.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
